language: php

php:
  - 7.2

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

env:
  - DATABASE_TEST_URL=null

before_install:
  - cd app

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - mysql -u root -p 'CREATE DATABASE test;'

script:
  - composer check